name: flutter-ci

on:
  workflow_call:
    inputs:
      flutter_channel:
        description: "Flutter channel"
        required: false
        type: string
        default: "stable"

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
          restore-keys: |
            ${{ runner.os }}-lfs-

      - name: Git LFS Pull
        run: git lfs pull

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.flutter_channel }}
          cache: true

      - name: Cache Pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Static Analysis
        run: flutter analyze

      - name: Run Tests
        run: flutter test
